### ISSUE TITLE
Disappearing Hands

### ISSUE THREAD

**Issue by BellaRoka** [coderCleric/Poltergeist#13]
After coming back from being a ghost I've noticed that my hands tend to disappear This makes the item I'm holding invisible and also makes AdvancedCompany's mini-terminal invisible.

**Comment by coderCleric** [comment]
Hm, weird, I haven't noticed that. Do you have a code for the mods you were using?

**Comment by BellaRoka** [comment]
I have a decently sized build, I wouldn't wanna make you dl and sift through all of it. I'll try doing some further testing to see if I can figure out if it might be a conflict between one of my other mods.

**Comment by coderCleric** [comment]
Any updates on this? Without more details I'll probably have to close the issue soon.

**Comment by coderCleric** [comment]
Closing as "won't implement" since I can't reproduce this without more details.
