### ISSUE TITLE
[Suggest] Add Config for Power

### ISSUE THREAD

**Issue by DHStyle541** [coderCleric/Poltergeist#14]
Hi, can you add the Config for Power?
I mean like Disabled Power when Ghost Mode or Min/Max Power 

and another suggest Add the UI Tooltips like SpectateEnemies + Speed When Ghost Mode

**Comment by coderCleric** [comment]
I hadn't even thought of the UI tooltips idea, that's a good one. I do plan to add config options for that kind of stuff once I get CSync figured out.

**Comment by coderCleric** [comment]
Resolved as of v1.0.0, although I'll need to make a separate issue for the tooltips.
