### ISSUE TITLE
[Suggest] Add up and down movement controls

### ISSUE THREAD

**Issue by allanjales** [coderCleric/Poltergeist#15]
Hi, since this is a free cam, can you add buttons to move vertically? Like space to get up and ctrl to get down since those keys are not been used in any form during free cam.

**Comment by coderCleric** [comment]
That would be a good idea.

**Comment by TheBlackEntity** [comment]
How would that work? Space up and Ctrl down?

**Comment by allanjales** [comment]
Like Minecraft's creative mode. When you hold the jump key in flying mode, it fly higher, and when you hold the crouch key, it descends. In Lethal Company, this feature could be similar.

**Comment by coderCleric** [comment]
Exactly. I'd probably make it so that, unless you're sprinting, using WASD wouldn't affect your elevation.

**Comment by TheBlackEntity** [comment]
> Exactly. I'd probably make it so that, unless you're sprinting, using WASD wouldn't affect your elevation.

I'd actually prefer a toggle, since both systems can be better in some scenarios

**Comment by coderCleric** [comment]
That's a fair idea, wouldn't be too difficult to implement. I'll probably have a key that you press to lock your elevation, making it so only the dedicated buttons can move you up and down in that state.

**Comment by coderCleric** [comment]
Closing as implemented as of v0.3.1.
