### ISSUE TITLE
Bug with the camera when there are more than 6 people in the team

### ISSUE THREAD

**Issue by BAHEK-BOP** [coderCleric/Poltergeist#16]
![image](https://github.com/coderCleric/Poltergeist/assets/157053836/b45e3050-4d73-499b-b1ed-56eb16d34cb4)
A bug with the camera occurs when there are 6+ players, less than everything is normal

I will write in more detail later

**Comment by BAHEK-BOP** [comment]
but my opinion is that I don't think it depends on the number of people. there are mods from plate company or shiplobby and mods with which they conflict (or maybe they don't, I don't know exactly which ones) just at 1 moment after half an hour or an hour of gameplay after your death, when you watch another player, the camera stops abruptly, and the person you were watching will run on (at everything is normal for him). it does not react to either the keyboard or the mouse, only alt f4 or hope that after the ship is in orbit, you will be scattered

**Comment by coderCleric** [comment]
So, after a certain amount of time post-death, the camera bugs out? Do you happen to have a list of mods you were using?

**Comment by BAHEK-BOP** [comment]
> So, after a certain amount of time post-death, the camera bugs out? Do you happen to have a list of mods you were using?

I don't think it's affected by any mod. It's just that when playing with 8-12 people, such an unpleasant thing happens

And so is the BMLC modpack

**Comment by coderCleric** [comment]
Okay, hm. Has it been recurring, and is there anything in common that multiple occurrences have besides having a lot of players? Also, if you can send the log file next time it happens that would be very helpful.

**Comment by coderCleric** [comment]
I'm gonna close this since I can't really replicate it without more details.
