### ISSUE TITLE
[Suggestion] Items + Features

### ISSUE THREAD

**Issue by Dsnherdude066** [coderCleric/Poltergeist#17]
All Items That Can Be Interacted With Not Just Noise Items

Items
Remote(Toggle Lights + Click), Robot(Robot Noise), Whoope(Woops), Teeth(Chatters), Rubber Duck(Squeaks), Old phone(Rings), Laser Pointer(on/off), (Pro/Norm)flash light(on/off), Hairdryer(Hair Dryer Noise), Gift box(Open), Fancy lamp(on/off), Double-barrel(fires), DIY-flashbang(activates), flashbang(activates), Radar-Booster(on/off), Extension Ladder(open/close)

Features
Config Energy, base(0-100) max(100-1000)
Client Side Toggle, lets you toggle if you want the mod to be fully client side(If Needed)
"Possess" lets you take as enemy's, not control, only talk

**Comment by coderCleric** [comment]
Definitely going to do some of these (being able to use more items does sound like a good time) and do plan to make more config options. I'm not sure if I'll implement all of these, but I will do a good deal of them.

**Comment by ChloeDawn** [comment]
To add to this, I think it would be cool if ghosts could close and open the ship door, maybe at a cost of 50, matching the requirement of toggling a powered door. And it would be great if you could trigger the teleporters - it has both potential for aid and for trolling, much like sound-making interactions. To pair with the teleporter interaction, maybe the monitor switching could be interactive too? I don't know what ideal costs for these interactions would be though.

**Comment by coderCleric** [comment]
I'm not sure on the teleporter and monitor stuff since the ship monitor doesn't always display properly, but ship doors is actually implemented and should roll out with the next update.

**Comment by Dsnherdude066** [comment]
@coderCleric can you add support for the levers on.... embrion? the new moon that looks like a military base
![image](https://github.com/coderCleric/Poltergeist/assets/126821288/1cf21dea-4afd-4f28-bd4f-ec3cd6fefe52)

**Comment by Dsnherdude066** [comment]
this one
![image](https://github.com/coderCleric/Poltergeist/assets/126821288/0fecdbd1-f9b5-4ba8-84c9-85f895d34843)

**Comment by coderCleric** [comment]
This is currently working in my development version and will be pushed out with the next update, which should be this weekend.

**Comment by coderCleric** [comment]
Gonna close as completed as of v1.1.0.
