### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RosinRush** [coderCleric/Poltergeist#18]
How about being able to manifest in some way to high-insanity players for a short time at the cost of power drain. 

Also, power seems to regen quite quickly.

**Comment by coderCleric** [comment]
I do like that manifesting idea. Probably won't be a thing this update since I don't understand the networked stuff yet, but should be a good idea for the future.

As for the power regen, next update should have more config options to tweak things like that.

**Comment by RosinRush** [comment]
Sounds great. 
Though, for manifesting, I was thinking maybe through an audio drone? 
Would that be hard to implement? 
(just, like, pressing 1 to toggle ghost sounds, maybe 2 gives you a second to say something, albeit extremely distorted)

**Comment by RosinRush** [comment]
That sounds really cool. 

Maybe you could make a ghost visor of some sort that worked similarly?

**Comment by coderCleric** [comment]
I'm not sure what you mean, like on the screens of ghosts? Kinda how living players can see the edges of the mask?

**Comment by RosinRush** [comment]
Oh, sorry, I meant glasses or something that let you see the ghost models while they're equipped instead of masking the models.

**Comment by coderCleric** [comment]
That could be a fun idea if I decide to do a little custom loot or something like that.

**Comment by coderCleric** [comment]
Closing as resolved as of v1.1.0.
