### ISSUE TITLE
Got stuck unable to interact or move. 

### ISSUE THREAD

**Issue by RosinRush** [coderCleric/Poltergeist#19]
Died and the mod just... did not do anything. No idea why.

**Comment by coderCleric** [comment]
Can you send the logoutput.txt file?

**Comment by coderCleric** [comment]
Also, when you say that you were unable to move, do you mean the camera was in the vanilla spectate mode or that the camera was entirely frozen in place?

**Comment by RosinRush** [comment]
I was able to swap between vanilla and poltergeist, but was entirely frozen in poltergeist.

**Comment by RosinRush** [comment]
> Can you send the logoutput.txt file?

Sorry, I only realized I should put in the bug report a while after it happened.

**Comment by coderCleric** [comment]
Hm, okay. Please send the file if this happens again. Unfortunately, I can't do much based on the information available right now, but I'll keep an eye on this issue in case you respond again.

**Comment by coderCleric** [comment]
Lmk if anything more comes of this, but I'm going to close it for now due to not being able to replicate.
