### ISSUE TITLE
[Suggestion] Add a key to toggle Poltergeist mode

### ISSUE THREAD

**Issue by TheBlackEntity** [coderCleric/Poltergeist#2]
I'd love to be able to toggle between the default spectator and Poltergeist.

This would also fix compatibility with mods like SpectateEnemies.

Maybe even add way to spectate in first person

**Comment by coderCleric** [comment]
This is one of the ones that I really want to add, just need to find the time. Probably not going to add a first person spectate though, because that's probably a good deal of work and I think already exists elsewhere.

**Comment by coderCleric** [comment]
Closing this issue as completed due to v0.2.0.
