### ISSUE TITLE
Cannot join servers without hosts having CSync

### ISSUE THREAD

**Issue by Nuzza** [coderCleric/Poltergeist#20]
I hate to be the bearer of bad news, but since v1.0.0 and the new CSync dependency, it is no longer possible to join servers without the host having CSync installed.

**Comment by coderCleric** [comment]
This is unfortunately just how that works. I have a bunch of stuff I want to do with the mod that will require network prefabs, which requires that everyone has the mod. For example, pestering enemies actually wouldn't work with how I used to do things.

**Comment by Nuzza** [comment]
@coderCleric thanks for the reply, would you ever consider creating a separate mod specifically for client side only (for those like me that want to be able to still use the mod on any server)? Or perhaps simply taking Poltergeist v0.3.1 and renaming it to Poltergeist (Legacy) or something.

FlipMods (the developer of TooManyEmotes) created a separate mod (in regards to the grabbable items update) as an addon for the main mod so that you still had the option to use the main mod client sided.

**Comment by Nuzza** [comment]
I only ask this as a lot of people may be confused that they cannot join many servers after updating to v1.0.0

**Comment by coderCleric** [comment]
I am considering it, especially since you aren't the first person to ask about it. I do have concerns with that though, in particular that some of the people requesting it are doing so on the grounds of things like "I can't lock random people behind powered doors anymore".
