### ISSUE TITLE
No Forward or Backwards Movement When Using LetMeLookDown

### ISSUE THREAD

**Issue by CupofJoe1** [coderCleric/Poltergeist#23]
Looking straight down with Flipmods' LetMelookDown prevents forward and backward camera movement with altitude lock on

https://thunderstore.io/c/lethal-company/p/FlipMods/LetMeLookDown/
<br>
**Steps to reproduce**
- Use LetMelookDown
- Enable Poltergeist cam upon death
- Enable altitude lock with keybind
- Look straight down
- Try to move forward and backwards with W and S

Side to side movement with A and D still work

**Comment by coderCleric** [comment]
Hm, that's weird, I'll look into it.

**Comment by coderCleric** [comment]
Should be fixed in the next release. Turns out it doesn't have anything to do with LetMeLookDown, was straight up just a Poltergeist bug.

**Comment by CupofJoe1** [comment]
Great. Sorry I didn't do much testing. Glad you got it sorted.
