### ISSUE TITLE
[Conflict] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by CoolLKKPS** [coderCleric/Poltergeist#25]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SpectateEnemy.SpectateEnemies.LateUpdate () (at <f5cb572518de4796a0d23214ca0c6bb7>:IL_025E)

**Comment by CoolLKKPS** [comment]
when u in ghost mode and specting enemy

**Comment by CoolLKKPS** [comment]
https://github.com/EBro912/SpectateEnemies/issues/14

**Comment by CoolLKKPS** [comment]
@coderCleric

**Comment by coderCleric** [comment]
I should really just take an in-depth look at the incompatibilities between SpectateEnemies and Poltergeist. Probably not this update (got other things planned), but maybe next one.
