### ISSUE TITLE
[Bug] Unknown issue with poltergeist freecam speed.

### ISSUE THREAD

**Issue by VioletXe** [coderCleric/Poltergeist#26]
I have no idea how this happens since it didn't happen to me, but over the course of a few hours and repeated deaths, my friend's poltergeist got exponentially slower. After 2 hours the "sprinting speed" was almost 10x slower than player walking. Is this a mod incompatibility or just an error?

**Comment by coderCleric** [comment]
Is it possible that they were using the decelerate button? By default it's "scroll down".

**Comment by coderCleric** [comment]
Without any more details I can't do anything about this, so I'm closing this issue.
