### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by RedsXX** [coderCleric/Poltergeist#28]
Says in the console that Poltergeist was not loaded because one of its dependencies "CSync" is missing. Version 5.x.x or higher.
I've tried multiple things and all have failed. Please help!
![image_2024-07-06_222800032](https://github.com/coderCleric/Poltergeist/assets/174919208/14e2f351-e984-40fd-bf0c-0c55194d8e5f)

**Comment by coderCleric** [comment]
You need to download the mod found [here](https://thunderstore.io/c/lethal-company/p/Sigurd/CSync/).

**Comment by RedsXX** [comment]
#

> You need to download the mod found [here](https://thunderstore.io/c/lethal-company/p/Sigurd/CSync/).

I tried that, didn't work. I had the mod before anyway.

**Comment by coderCleric** [comment]
Is the log giving any errors related to csync? Do you have the dependencies that csync needs? If you can send your logoutput.txt file that would help as well.

**Comment by RedsXX** [comment]
```
[Message:   BepInEx] BepInEx 5.4.21.0 - Lethal Company (12/4/2023 7:34:17 PM)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] Loaded 1 patcher method from [FixPluginTypesSerialization 1.0.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Message:FixPluginTypesSerialization] Using the config cache
[Info   :FixPluginTypesSerialization] Running under Unity v2022.3.9
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [Lethal Company Input Utils 0.7.7]
[Info   :Lethal Company Input Utils] Registered InputUtilsExtendedMouse Layout Override!
[Info   :Lethal Company Input Utils] InputUtils 0.7.7 has finished loading!
[Error  :   BepInEx] Could not load [Poltergeist 1.1.0] because it has missing dependencies: com.sigurd.csync (v5.0.1 or newer)
[Message:   BepInEx] Chainloader startup complete

```
I isolated the mod with the dependencies, this is the log. To me, it looks like its not even detecting Csync is there.
![image](https://github.com/coderCleric/Poltergeist/assets/174919208/355588d4-ab87-412b-a6ae-0c4e042da2e5)
This is the mod list.

**Comment by coderCleric** [comment]
Hm, yeah, it's not loading csync at all for some reason. Maybe try uninstalling and reinstalling csync?

**Comment by RedsXX** [comment]
Tried that earlier, didn't work.

**Comment by coderCleric** [comment]
That's really weird. I'm not sure I can do much about csync just not being recognized. Have you tried asking about it on the modding discord? People there might know more about mod loader problems than I do.

**Comment by RedsXX** [comment]
Hey, I just solved it! I went into my profiles file and found that CSync only had the icon, so I manually downloaded it and put the dll file in myself. Thanks for your help.

**Comment by coderCleric** [comment]
Huh, weird. Glad you were able to figure it out! I'll go ahead and close this as resolved.
