### ISSUE TITLE
Poltergeists aren't able to play sounds using woopie cushions, plushes etc.

### ISSUE THREAD

**Issue by AlexGM311** [coderCleric/Poltergeist#29]
I'm going to guess that this error on load has to do something with it:
[Error  : Unity Log] TypeLoadException: Could not load type WhoopieCushionTrigger, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)
Stack trace:
System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) (at <787acc3c9a4c471ba7d971300105af24>:IL_0013)
System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) (at <787acc3c9a4c471ba7d971300105af24>:IL_0037)
System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Boolean inherit) (at <787acc3c9a4c471ba7d971300105af24>:IL_0024)
System.Reflection.RuntimeMethodInfo.GetCustomAttributes (System.Boolean inherit) (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
HarmonyLib.PatchTools+<>c__DisplayClass2_0.<GetPatchMethod>b__0 (System.Reflection.MethodInfo m) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) (at <dab7f68612224ba3ae40f651d44f9d4c>:IL_003F)
System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <dab7f68612224ba3ae40f651d44f9d4c>:IL_0000)
HarmonyLib.PatchTools.GetPatchMethod (System.Type patchType, System.String attributeName) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0018)
HarmonyLib.PatchClassProcessor..ctor (HarmonyLib.Harmony instance, System.Type type, System.Boolean allowUnannotatedType) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_00A4)
HarmonyLib.PatchClassProcessor..ctor (HarmonyLib.Harmony instance, System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
HarmonyLib.Harmony.CreateClassProcessor (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0014)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0006)
HarmonyLib.Harmony.CreateAndPatchAll (System.Reflection.Assembly assembly, System.String harmonyInstanceId) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_001E)
Poltergeist.Poltergeist.Awake () (at <5641ab881f8a40978b718bc46bf3d695>:IL_001B)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()

The error on startup occurs only on v60, though I noticed the problem in v55

**Comment by coderCleric** [comment]
Hm, okay. I'll take a look at it when I get a chance.

**Comment by coderCleric** [comment]
Marking as resolved as of v1.1.1.
