### ISSUE TITLE
[Bug?] Global light barely works inside

### ISSUE THREAD

**Issue by TheBlackEntity** [coderCleric/Poltergeist#3]
When inside the facility, the global light barely does anything to the darkness.

It does work quite well outside.

Not sure if this is intentional, hence the question mark

**Comment by coderCleric** [comment]
Hm, not sure I've noticed that myself. Do you mind clarifying a couple of things:
- Were you inside the mansion layout or the facility layout?
- Was the last person you teleported to inside as well? If you hadn't teleported to anyone that death, did you die inside?
- Did you notice if the light wasn't turning on at all, or was it just dim?

**Comment by TheBlackEntity** [comment]
> Were you inside the mansion layout or the facility layout?

This is an issue with all interiors

> Was the last person you teleported to inside as well?

Yes

> If you hadn't teleported to anyone that death, did you die inside?

It doesn't seem to matter where I died

> Did you notice if the light wasn't turning on at all, or was it just dim?

I did notice it, but very dim, so it basically didn't change anything.

I'll ad some screenshots when I play again ^^

**Comment by coderCleric** [comment]
Appreciated. I think it might just be a matter of us playing on different graphics settings. I'll probably throw in a config option to change the intensity of the global light, so users can curate it a bit more to what works best for them.

**Comment by coderCleric** [comment]
Added this option in v0.1.1.
