### ISSUE TITLE
[Issue] Mod creature will throw error

### ISSUE THREAD

**Issue by CoolLKKPS** [coderCleric/Poltergeist#32]
![1731427810405](https://github.com/user-attachments/assets/147a089b-859a-4361-a844-09382ba58c0f)

@coderCleric bc this, if u can, can u add some config that can `specify some creature` can able to interact, this config will auto-generate all detected creature

**Comment by coderCleric** [comment]
I might implement something like a blacklist so you can specify enemies that won't be made interactible. I have noticed though that the mod will occasionally throw that error for random enemies, I'm really not sure why. Might not be a specific issue with that modded creature though.

**Comment by CoolLKKPS** [comment]
ok uh, how i can disable that feature? i set this feature require 999 power, but still throw error

**Comment by coderCleric** [comment]
The bad news is that there's no option to disable the interaction, so you can't stop that error. The good news is that the only thing that error should actually do is make it so ghosts can't interact with that enemy.

**Comment by CoolLKKPS** [comment]
nice, enough for me, thx for the reply
this issue question is actually to address my friend's concerns, which he has been susing about this for the past week but he don't know english, so he say this mod can affect the spike trap, which cause ghost can trigged the spike trap, and jester won't return to stage 1 when after everyone go outdoor and jester already stage 3, idk he's a bit paranoid, im still testing, im susing this issue is from mod creature at the first time

**Comment by CoolLKKPS** [comment]
after 9 hrs test, no further issue found, only this error for now

**Comment by coderCleric** [comment]
I would be very surprised if either of those issues happened, I don't think that ghosts have the stuff necessary to cause either.
