### ISSUE TITLE
Black screen when in multiplayer

### ISSUE THREAD

**Issue by Apollonu** [coderCleric/Poltergeist#35]
When it is played in multiplayer, anyone who joins gets a black screen and their model doesnt load.

**Comment by coderCleric** [comment]
Are you sure that this is caused by Poltergeist? I've used it on the current version and didn't encounter that issue. If you can, send the log file when this occurs.

**Comment by Apollonu** [comment]
My friend was getting this spammed every frame with poltergeist enabled
[Warning: Unity Log] [Netcode] NetworkObject (2) children not resolved to parents by the end of frame
[Info   : Unity Log] soumdmanager: True; False

When we disable poltergeist it works fine

**Comment by Apollonu** [comment]
This could be a CSync issue as Arachnophilia has a similar issue with people not joining and having a black screen

**Comment by coderCleric** [comment]
Hm, okay, I'll look into it.

**Comment by coderCleric** [comment]
I can't figure out what it causing your issue, but I don't think it's caused directly by Poltergeist. 

When I boot your modpack (with or without Poltergeist) I see a massive error for FixPluginTypesSerialization that could be causing problems? I really don't know though, with a big modpack like this that throws a bunch of errors whether or not it runs fine it's difficult to tell what mods are conflicting. 

I will say that Poltergeist works fine in my modpack, so I think it's not an inherent issue with the mod.

**Comment by Apollonu** [comment]
If I can find the incompatible mod, i'll respond here with it

**Comment by Apollonu** [comment]
Also CSync requires FixPluginTypesSerialization

**Comment by Apollonu** [comment]
This was caused by deleting FixPluginTypesSerialization config
