### ISSUE TITLE
[BUG] change speed adjustment default linked keybind

### ISSUE THREAD

**Issue by CoolLKKPS** [coderCleric/Poltergeist#5]
@coderCleric 
i use 1 and 3 key to switch items, and that conflict with speed adjustment in this mod bc that will trigger tp to player

**Comment by coderCleric** [comment]
It won't make it into this update, but I will find some way to resolve this issue. I'll probably make it so that the teleporting works based on cycling through targets, then teleporting to the targeted player. I have played with the idea of having the speed adjustment linked to a keyboard key, but it was clunky since you would need to move a hand to adjust it.

**Comment by CoolLKKPS** [comment]
usually user won't use speed adjustment too often just like a game call Battlefield (except speed are way too slow), usually user want to instantly speed up in spectator mode just like sprint; and also u can try to use controller, or rebind "Store furniture" and "Replace furniture" keys if feel clunky, that way will always have the solution

**Comment by CoolLKKPS** [comment]
> Why not use https://thunderstore.io/c/lethal-company/p/Rune580/LethalCompany_InputUtils/. Many popular mods are using this one.

i was thinking about this before, if can able to not conflict with other keybinds by default that will be great, i agree

**Comment by coderCleric** [comment]
Hm, okay, I'll look into that one.

**Comment by coderCleric** [comment]
Okay, yeah, this should be really helpful, thanks for pointing it out! I probably won't allow fully separated binding (no reason to have interact be bound to different keys when alive vs dead), but it will definitely be useful for things like the speed adjustment.

**Comment by CoolLKKPS** [comment]
@coderCleric 
yea but not just the keybind issues unfortunately, if u have multiple players, in ur lobby, u can try my "among us" idea in [here](https://github.com/coderCleric/Poltergeist/issues/9)

**Comment by coderCleric** [comment]
I'm honestly thinking of implementing a teleporting method that lets you cycle through target players, then press a secondary button to teleport to the targeted one. A dedicated UI menu for it would probably be better honestly, but is outside of the scope of what I have time for rn, honestly.

**Comment by CoolLKKPS** [comment]
> I'm honestly thinking of implementing a teleporting method that lets you cycle through target players, then press a secondary button to teleport to the targeted one.

i previous was thinking, if have UI interface just like among us style would be better, but since other mods already try that and didn't looks good (won't lock the cam), so yea this time i agree with u, will recall some feedback, but keybind issues still there tho

**Comment by coderCleric** [comment]
I've actually just now gotten InputUtils working on my end, so the next update will have reconfigurable keybinds for toggling the ghost light, acceleration, deceleration, and switching spectate modes.

**Comment by CoolLKKPS** [comment]
> I've actually just now gotten InputUtils working on my end, so the next update will have reconfigurable keybinds for toggling the ghost light, acceleration, deceleration, and switching spectate modes.

nice, yes thats a good news, keep up the good work!

**Comment by coderCleric** [comment]
Resolved in 0.3.0.
