### ISSUE TITLE
[Suggestion] add "ghost" keyword in mod secondary title, make the ghost visiable when in ghost mode, and keybinds, etc.

### ISSUE THREAD

**Issue by CoolLKKPS** [coderCleric/Poltergeist#9]
add "ghost" keyword in mod secondary title to let mod can more easier to search, for now it just say "Lets players freecam on death and mess with certain objects."
 \- i know ghostmode mod, is pretty impossible to avoid conflict;
what i expect is, Poltergeist will require all user who installed this mod to have the same config, which mean need CSync;
 \- all object that able to interact by the ghost is configurable (limit or not)
u can see other ghost when u are a ghost, so u can try to find other ghost in afterlife or just simply tp to other ghost
 \- one of the ghost can help to block the hit, just like what among us angel doing, configurable
add interact and block dmg cooldown, configurable
> add keybinds to let u cycle through target players, then press a secondary button to teleport to the targeted one
> \- that actually can make more trouble if user using custom keybinds, for some user who really want default setup is enough to use just like me

**Comment by coderCleric** [comment]
Thanks for the tip on the CSync mod, that should definitely be useful. I do want to do synced configs (probably in an update or two), but I think a lot of this might be outside of the scope of what I really have time for.

**Comment by coderCleric** [comment]
I'm going to make multiple issues for each of the individual points of this one, then close this one.

**Comment by CoolLKKPS** [comment]
nah feel free to take those suggestion, but really, this mod can be better, so i will keep this mod in my modpack
